import{a as b,S as q,i as n}from"./assets/vendor-DxEWe7lX.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const P="50252354-e48f782526adef10354766461",E="https://pixabay.com/api/",$=15,u=async(o,e=1)=>{const r={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:$};return(await b.get(E,{params:r})).data},m=document.querySelector(".gallery"),p=document.querySelector(".loader"),f=document.querySelector(".load-more");let d;const h=o=>{const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p>Likes <span>${r.likes}</span></p>
        <p>Views <span>${r.views}</span></p>
        <p>Comments <span>${r.comments}</span></p>
        <p>Downloads <span>${r.downloads}</span></p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",e),d?d.refresh():d=new q(".gallery a")},B=()=>{m.innerHTML=""},y=()=>p.classList.remove("hidden"),g=()=>p.classList.add("hidden"),M=()=>f.classList.remove("hidden"),L=()=>f.classList.add("hidden"),w=document.querySelector(".form"),A=w.elements["search-text"],H=document.querySelector(".load-more");let i="",a=1,v=0;const S=15;w.addEventListener("submit",async o=>{if(o.preventDefault(),i=A.value.trim(),!i){n.warning({message:"Please enter a search query!"});return}a=1,B(),L(),y();try{const e=await u(i,a);if(v=e.totalHits,e.hits.length===0){n.info({message:"Sorry, there are no images matching your search query."});return}h(e.hits),e.totalHits>S&&M()}catch{n.error({message:"Something went wrong..."})}finally{g()}});H.addEventListener("click",async()=>{a+=1,y();try{const o=await u(i,a);h(o.hits),O();const e=Math.ceil(v/S);a>=e&&(L(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Failed to load more images."})}finally{g()}});function O(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
